name:
  - usatlas-argonne-python
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - uproot
  - pandas
  - matplotlib
  - pytorch-cpu
  - numexpr
  - numba
  - root
  - h5py
  - pyarrow
  - pip:
      - root_numpy
